# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  perfspec: "nothing"    # this is available to all jobs

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $(perfspec)

- script: |
    sudo apt update 
    sudo apt install nodejs
    sudo apt install npm
    sudo apt install jq
  displayName: Install Node and NPM

- script: |
    npm version
  displayName: Check if nodejs is installed
  
- script: |
    npm install
  displayName: Package pitometer

- script: |
    export DYNATRACE_BASEURL="https://xiz610.dynatrace-managed.com/e/1576d48e-6811-4f07-af4b-c6345c5e7c41"
    export DYNATRACE_APITOKEN="bGDrn1f_SI-ge2R9P-JLF"
    node pitometer.js -s 1573542578 -e 1573542754 -p ./samples/perfspec-kbi.json | tail -n +5 > pitometer_output.json
    jq '.' pitometer_output.json
  displayName: Run pitometer validation on KBI

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'