# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  perfspec: "nothing"    # this is available to all jobs

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $(perfspec)

- script: |
    sudo apt update 
    sudo apt install nodejs
    sudo apt install npm
  displayName: Install Node and NPM

- script: |
    npm version
  displayName: Check if nodejs is installed

- script: |
    docker pull mvilliger/pitometer-cli
  displayName: Run pitometer validation on KBI
