# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  perfspec: "nothing"    # this is available to all jobs

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo $(perfspec)

- script: |
    sudo apt update 
    sudo apt install nodejs
    sudo apt install npm
    sudo apt install jq
  displayName: Install Node and NPM

- script: |
    npm version
  displayName: Check if nodejs is installed
  
- script: |
    npm install
  displayName: Package pitometer

- script: |
    CURRENT_TIME=$(printf "%(%s)T")
    START_TIME=$(printf "$(( $(printf "%(%s)T") - 360 * 60 ))")
    node pitometer.js -s $START_TIME -e $CURRENT_TIME -p ./samples/perfspec-springmusic.json | tail -n +5 > pitometer_output.json
    jq '.' pitometer_output.json
  displayName: Run pitometer validation on KBI
